apiVersion: v1
kind: Service
metadata:
  name: retail-service
  labels:
    app: retail-shelf-app
spec:
  type: ClusterIP
  selector:
    app: retail-shelf-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
