apiVersion: apps/v1
kind: Deployment
metadata:
  name: retail-app
  labels:
    app: retail-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: retail-app
  template:
    metadata:
      labels:
        app: retail-app
    spec:
      containers:
      - name: retail-app
        image: preetisoundaryaa/myretail-app:latest
        ports:
        - containerPort: 8000
        env:
        - name: FLASK_ENV
          value: "production"
