{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "myretail.fullname" . }}
  labels:
    {{- include "myretail.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className | quote }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.path | quote }}
            pathType: {{ .Values.ingress.pathType | quote }}
            backend:
              service:
                name: {{ include "myretail.serviceName" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}
