apiVersion: v1
kind: Service
metadata:
  name: {{ include "myretail.serviceName" . }}
  labels:
    {{- include "myretail.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "myretail.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
