{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.prometheus.serviceAccount.name }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.prometheus.clusterRole.name }}
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes", "services", "endpoints"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.prometheus.clusterRoleBinding.name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.prometheus.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.prometheus.clusterRole.name }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
