apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myretail
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/preetisoundaryaa/myRetailProject.git
    targetRevision: main
    path: helm/myretail
    helm:
      releaseName: myretail
  destination:
    server: https://kubernetes.default.svc
    namespace: retail
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
