name: Build and Push Docker Image

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set image tag
        id: vars
        run: echo "TAG=${GITHUB_SHA::7}" >> "$GITHUB_ENV"

      - name: Print tag info
        run: |
          echo "Full SHA: $GITHUB_SHA"
          echo "Short TAG: $TAG"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        id: build_push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          no-cache: true
          tags: ${{ secrets.DOCKER_USERNAME }}/myretail-app:${{ env.TAG }}

      - name: Show image digest
        run: echo "Digest = ${{ steps.build_push.outputs.digest }}"

      - name: Update Helm values.yaml
        run: |
          sed -i "s/tag:.*/tag: \"${TAG}\"/" helm/retail-app/values.yaml

      - name: Commit and push Helm changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add helm/retail-app/values.yaml
          git commit -m "Update image tag to ${TAG}" || echo "No changes to commit"
          git push
